export const premiumMoicStyles = {
  fontFamily: 'Arial, Helvetica, sans-serif',
  borderColor: '#cbd5e1',
  borderStyle: '1px solid #cbd5e1',
  
  header: {
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontWeight: 'bold' as const,
    fontSize: '13px',
    padding: '10px 14px',
    textAlign: 'left' as const,
    border: '1px solid #334155',
  },
  headerNumeric: {
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontWeight: 'bold' as const,
    fontSize: '13px',
    padding: '10px 14px',
    textAlign: 'right' as const,
    border: '1px solid #334155',
  },
  
  cellProduct: {
    backgroundColor: '#f1f5f9',
    color: '#0f172a',
    fontWeight: '600' as const,
    fontSize: '13px',
    padding: '9px 14px',
    border: '1px solid #cbd5e1',
    textAlign: 'left' as const,
  },
  cellDefaultNumeric: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    fontSize: '13px',
    padding: '9px 14px',
    border: '1px solid #cbd5e1',
    textAlign: 'right' as const,
  },
  cellPctOfFace: {
    backgroundColor: '#1e293b',
    color: '#ffffff',
    fontWeight: 'bold' as const,
    fontSize: '13px',
    padding: '9px 14px',
    border: '1px solid #0f172a',
    textAlign: 'right' as const,
  },
  cellMoic: {
    backgroundColor: '#e0f2fe',
    color: '#0369a1',
    fontWeight: 'bold' as const,
    fontSize: '13px',
    padding: '9px 14px',
    border: '1px solid #bae6fd',
    textAlign: 'right' as const,
  },
};
